services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app  # Updated to match your file name
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - annotations:/app/annotations  # Persist annotations
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sat_annotator
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Added --reload for dev

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sat_annotator
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  annotations:  # Added for persistent annotations