services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads  # For image uploads
      - annotations:/app/annotations  # For annotation data
    environment:
      - ENVIRONMENT=development
      - SESSION_SECRET=your_session_secret_key_here
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  annotations: