services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - annotations:/app/annotations
    environment:
      - ENVIRONMENT=development
      - SESSION_SECRET=your_session_secret_key_here
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/web
      - /web/node_modules
    working_dir: /web
    environment:
      - VITE_API_URL=/api  # Now uses proxy
    depends_on:
      - backend

volumes:
  annotations:
