name: App Tests

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
  pull_request:
    branches: [main]
    paths:
      - 'app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f app/tests/test_requirements.txt ]; then pip install -r app/tests/test_requirements.txt; fi
        pip install -r app/requirements_simplified.txt
    
    - name: Set test mode environment variable
      run: |
        echo "SAT_ANNOTATOR_TEST_MODE=1" >> $GITHUB_ENV
    
    - name: Run unittest tests
      run: |
        cd app/tests
        python run_unittests.py
